source "https://rubygems.org"

# Jekyll y su tema
gem "jekyll", "~> 4.3.4"
gem "minima", "~> 2.5.2"  # Asegúrate de que esta sea la última versión compatible
gem "jekyll-theme-simplex", "~> 0.9.8"

# Plugins de Jekyll
gem "jekyll-feed", "~> 0.17.0"  # Asegúrate de usar una versión compatible

# Dependencias para plataformas específicas
group :jekyll_plugins do
  gem "jekyll-watch"  # Agrega este plugin si lo necesitas
end

# Dependencias para Windows
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
  gem "wdm", "~> 0.1"
end

# Dependencias para JRuby
gem "http_parser.rb", "~> 0.6.0", platforms: [:jruby]
